---
title: "Teaching"

---

During the last 4 years I had the pleasure of teaching multiple courses in the sociology bachelor of the University of Groningen in my third language, Dutch. I assisted Prof. Andreas Flache with his course "Inleiding Socialogie" (Introduction to Sociology) in which we discuss sociological theories and research at the example of societal problems with all first year Sociology students.

Next to that I taught a course on academic and research skills ("Europeese Waarden"). In this course we walk students through the full research circle and they learn how to read literature, formulate research questions, conduct regression analysis and write a research paper. It is an extensive half year course with weekly lectures, workshops and individual feedback on biweekly assignments. 

I also had the pleasure to supervise bachelor and master thesis of Sociology students, as well as traineeships and thesis of a Research Master student. This one on one supervision is most insightful for both students and teacher and was among the most enjoyable teaching experiences at the Department of Sociology.